services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pitchlab
    ports:
      - "5432:5432"
    volumes:
      - pitchlab_pgdata:/var/lib/postgresql/data
volumes:
  pitchlab_pgdata:
